version: '3.9'

services:
  waf:
    build:
      context: .
    container_name: waf
    command: python waf_proxy.py
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb+srv://ayesha00zafar:Sherni@cluster0.p0gakkw.mongodb.net/
    networks:
      - waf-net

  worker:
    build:
      context: .
    container_name: waf-worker
    command: celery -A worker.app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb+srv://ayesha00zafar:Sherni@cluster0.p0gakkw.mongodb.net/
    networks:
      - waf-net

  redis:
    image: redis
    container_name: waf-redis
    ports:
      - "6379:6379"
    networks:
      - waf-net

  # Optional: Nginx reverse proxy setup
  # nginx:
  #   image: nginx:alpine
  #   container_name: waf-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - waf
  #   networks:
  #     - waf-net

networks:
  waf-net:
    driver: bridge



