version: '3.9'

services:
  waf:
    build:
      context: .
    container_name: waf
    ports:
      - "8080:8080"  
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
      - PORT=8080           
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=your-mongo-uri-here  

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: waf-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - waf

networks:
  default:
    driver: bridge



